version: '3.7'

services:
  db:
    image: mongo:5.0.0
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
